name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        cfg: [Release]
    env:
      CFG: ${{ matrix.cfg }}
    defaults:
      run:
        shell: cmd
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Cache object files
        id: windows-cache
        uses: actions/cache@v3
        with:
          path: |
            D:/a/wesnoth/vcpkg
            D:/a/wesnoth/wesnoth/vcpkg_installed
          key: win-cache-master-${{ matrix.cfg }}-0001

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

# checkout a specific commit to prevent cmake from thinking it can't use the cached dependencies anymore
# the commit itself is just whatever happens to be the latest commit when a newer version is needed
      - name: Build vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git D:/a/wesnoth/vcpkg
          cd D:/a/wesnoth/vcpkg
          git checkout 151c42c5f4ec5f8b7c59369ad412ad5812643929
          cp ${{ github.workspace }}/vcpkg-tool-metadata.txt ./scripts/vcpkg-tool-metadata.txt
          D:/a/wesnoth/vcpkg/bootstrap-vcpkg.bat

      - name: Run vcpkg install manually to debug
        run: D:/a/wesnoth/vcpkg/vcpkg.exe install --debug --dry-run

