name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        cfg: [Release]
    env:
      CFG: ${{ matrix.cfg }}
    defaults:
      run:
        shell: cmd
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Cache object files
        id: windows-cache
        uses: actions/cache@v3
        with:
          path: |
            D:/a/wesnoth/vcpkg
            D:/a/wesnoth/wesnoth/vcpkg_installed
          key: win-cache-master-${{ matrix.cfg }}-0001

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

# checkout a specific commit to prevent cmake from thinking it can't use the cached dependencies anymore
# the commit itself is just whatever happens to be the latest commit when a newer version is needed
      - name: Build vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git D:/a/wesnoth/vcpkg
          cd D:/a/wesnoth/vcpkg
          git checkout 151c42c5f4ec5f8b7c59369ad412ad5812643929
          echo "VCPKG_TOOL_RELEASE_TAG=2023-08-02" > D:/a/wesnoth/vcpkg/scripts/vcpkg-tool-metadta.txt
          echo "VCPKG_MACOS_SHA=3698a1bbd3c3d5228d5536c2f6c6a8b98ce99deb0fe55c79b5fc9d1af506350494bea326caa3018afeb7bd794a47d612c949cceb836e4f2c39c2e2bbe7a48dcf" >> D:/a/wesnoth/vcpkg/scripts/vcpkg-tool-metadta.txt
          echo "VCPKG_MUSLC_SHA=5b7c2c9e691706c12b0c183b9245f44eb26e3b2b1fb30702b634c86832fdf9afef4bba2f50327b1b95873a8d519fcd0b0a9184d79c3c5f5ba9c2f0b510821313" >> D:/a/wesnoth/vcpkg/scripts/vcpkg-tool-metadta.txt
          echo "VCPKG_GLIBC_SHA=d8719c9edc79dd31cf362c6f9bda6b342c42df640cb76d4473eb913af56f8eff9ca5a9753e878e004a0673f588dc76eb3b32e7888f1583a019ed4973e9767379" >> D:/a/wesnoth/vcpkg/scripts/vcpkg-tool-metadta.txt
          echo "VCPKG_TOOL_SOURCE_SHA=afb17e1a369450738095ebdddc4618ae5588731b7204132f0f5353793ccd5068d6d39c2a80fb1d3c56119ab4e788e69d80b47dbbacbcd299c5029739d562dbaa" >> D:/a/wesnoth/vcpkg/scripts/vcpkg-tool-metadta.txt
          cat D:/a/wesnoth/vcpkg/scripts/vcpkg-tool-metadata.txt
          D:/a/wesnoth/vcpkg/bootstrap-vcpkg.bat

      - name: Run vcpkg install manually to debug
        run: D:/a/wesnoth/vcpkg/vcpkg.exe install --debug

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.20.6'

      - name: Run cmake
        run: |
          cmake -DCMAKE_BUILD_TYPE=%CFG% -DENABLE_GAME=true -DENABLE_SERVER=true -DENABLE_CAMPAIGN_SERVER=true -DENABLE_TESTS=true -DENABLE_MYSQL=false -DENABLE_NLS=false -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_TOOLCHAIN_FILE=D:/a/wesnoth/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_GENERATOR_PLATFORM=x64 -G "Visual Studio 16 2019" .

# delete buildtrees directory to free up space after cmake invokes vcpkg to build the dependencies
# otherwise the job was failing when trying to write a .obj file
# building vcpkg on the more spacious C drive didn't work since for some reason vcpkg decides to not create the pango/cairo pkgconfig files there
      - name: Build wesnoth, wesnothd, campaignd and unit tests
        run: |
          rmdir /s /q D:\a\wesnoth\vcpkg\buildtrees
          MSBuild.exe wesnoth.sln -p:Configuration=%CFG%

      - name: Run WML unit tests
        if: matrix.cfg == 'Release'
        run: python run_wml_tests -v -g -c -t 20 -p D:/a/wesnoth/wesnoth/%CFG%/wesnoth.exe
